create table opt_table
(
  id               VARCHAR(200) comment '主键' primary key,
  type             VARCHAR(200) not null comment '操作类型',
  user_id          VARCHAR(200) not null comment '用户id',
  policy_id        VARCHAR(200) not null comment '策略id',
  fund_code        VARCHAR(200) not null comment '基金代码',
  date0            VARCHAR(200) not null comment '日期',
  before_close     DOUBLE default 0.0 comment '前一日的close值',
  now_close        DOUBLE default 0.0 comment '当前close值',
  deal_price       DOUBLE default 0.0 comment '交易价格',
  deal_account     DOUBLE default 0.0 comment '交易份数',
  create_time      VARCHAR(200) comment '创建时间',
  sum_account      DOUBLE default 0.0 comment '当前持有总份数',
  now_money        DOUBLE default 0.0 comment '当前持有份额的总市值',
  input_money      DOUBLE default 0.0 comment '本周期投入总值',
  float_money      DOUBLE default 0.0 comment '本周期浮动金额',
  float_rate       DOUBLE default 0.0 comment '本周期浮动比例',
  close0           DOUBLE default 0.0 comment '当日close值',
  close_max        DOUBLE default 0.0 comment '20日最高值',
  back_rate        DOUBLE default 0.0 comment '回调阈值比例',
  deviate_standard DOUBLE default 0.0 comment '年线偏移比例标准值',
  deviate_rate     DOUBLE default 0.0 comment '年线偏移率',
  input_all        DOUBLE default 0.0 comment '总投入',
  now_all          DOUBLE default 0.0 comment '当前总值',
  surplus          DOUBLE default 0.0 comment '活期余额',
  surplus_interest DOUBLE default 0.0 comment '活期余额利率',
  make_all         DOUBLE default 0.0 comment '总盈利额',
  day0             DOUBLE comment '持有0天的份额',
  day1             DOUBLE comment '持有1天的份额',
  day2             DOUBLE comment '持有2天的份额',
  day3             DOUBLE comment '持有3天的份额',
  day4             DOUBLE comment '持有4天的份额',
  day5             DOUBLE comment '持有5天的份额',
  day6             DOUBLE comment '持有6天的份额',
  day7             DOUBLE comment '持有满7天的份额,可交易',
  update_date      VARCHAR(200) comment '更新日期',
  update_time      VARCHAR(200) comment '更新时间',
  status           VARCHAR(200) comment '状态'
) comment '操作记录表' default charset=utf8;
