create table policy_fund
(
  id               VARCHAR(200) comment '主键' primary key,
  policy_id        VARCHAR(200) comment '策略id',
  fund_code        VARCHAR(200) comment '基金代码',
  fund_name        VARCHAR(200) comment '基金名称',
  sum_account      DOUBLE default 0.0 comment '当前持有总份数',
  now_money        DOUBLE default 0.0 comment '当前持有份额的总市值',
  input_money      DOUBLE default 0.0 comment '本周期投入总值',
  float_money      DOUBLE default 0.0 comment '本周期浮动金额',
  float_rate       DOUBLE default 0.0 comment '本周期浮动比例',
  close0           DOUBLE default 0.0 comment '当日close值',
  close_max        DOUBLE default 0.0 comment '20日最高值',
  back_rate        DOUBLE default 0.0 comment '回调阈值比例',
  deviate_standard DOUBLE default 0.0 comment '年线偏移比例标准值',
  deviate_rate     DOUBLE default 0.0 comment '年线偏移率',
  day0             DOUBLE default 0.0 comment '持有0天的份额',
  day1             DOUBLE default 0.0 comment '持有1天的份额',
  day2             DOUBLE default 0.0 comment '持有2天的份额',
  day3             DOUBLE default 0.0 comment '持有3天的份额',
  day4             DOUBLE default 0.0 comment '持有4天的份额',
  day5             DOUBLE default 0.0 comment '持有5天的份额',
  day6             DOUBLE default 0.0 comment '持有6天的份额',
  day7             DOUBLE default 0.0 comment '持有满7天的份额,可交易',
  create_time      VARCHAR(200) comment '记录创建时间',
  update_date      VARCHAR(200) comment '更新日期',
  update_time      VARCHAR(200) comment '更新时间',
  status           VARCHAR(200) comment '状态'
) comment '策略对基金明细表' default charset=utf8;
