CREATE TABLE `index_history` (
  `id` varchar(200) NOT NULL COMMENT '主键',
  `index_code` varchar(200) DEFAULT NULL COMMENT '指数代码',
  `date0` varchar(200) DEFAULT NULL COMMENT '日期',
  `close0` double DEFAULT '0' COMMENT '收盘点数',
  `PE_add` double DEFAULT NULL COMMENT '加权PE',
  `PE_add_rate` double DEFAULT '0' COMMENT '加权PE百分位',
  `PE_add_30` double DEFAULT NULL COMMENT '加权PE机会值(30分位)',
  `PE_add_70` double DEFAULT NULL COMMENT '加权PE危险值(70分位)',
  `PE_avg` double DEFAULT NULL COMMENT '均权PE',
  `PE_avg_rate` double DEFAULT '0' COMMENT '均权PE百分位',
  `PE_avg_30` double DEFAULT NULL COMMENT '均权PE机会值(30分位)',
  `PE_avg_70` double DEFAULT NULL COMMENT '均权PE危险值(70分位)',
  `PB_add` double DEFAULT NULL COMMENT '加权PB',
  `PB_add_rate` double DEFAULT '0' COMMENT '加权PB百分位',
  `PB_add_30` double DEFAULT NULL COMMENT '加权PB机会值(30分位)',
  `PB_add_70` double DEFAULT NULL COMMENT '加权PB危险值(70分位)',
  `PB_avg` double DEFAULT NULL COMMENT '均权PB',
  `PB_avg_rate` double DEFAULT '0' COMMENT '均权PB百分位',
  `PB_avg_30` double DEFAULT NULL COMMENT '均权PB机会值(30分位)',
  `PB_avg_70` double DEFAULT NULL COMMENT '均权PB危险值(70分位)',
  `ROE` double DEFAULT NULL COMMENT '净资产收益率',
  `ROE_avg_rate` double DEFAULT '0' COMMENT 'ROE百分位',
  `ROE_30` double DEFAULT NULL COMMENT 'ROE机会值(30分位)',
  `ROE_70` double DEFAULT NULL COMMENT 'ROE危险值(70分位)',
  `avg_5` double DEFAULT NULL COMMENT '5日均值',
  `avg_10` double DEFAULT NULL COMMENT '10日均值',
  `avg_20` double DEFAULT NULL COMMENT '20日均值',
  `avg_60` double DEFAULT NULL COMMENT '60日均值',
  `avg_120` double DEFAULT NULL COMMENT '120日均值',
  `avg_250` double DEFAULT NULL COMMENT '250日均值',
  `create_time` varchar(200) DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `close0` (`close0`),
  KEY `date0` (`date0`) USING BTREE,
  KEY `indexCode_date0` (`index_code`,`date0`) USING BTREE,
  KEY `indexCode_close0` (`index_code`,`close0`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='指数历史表';